<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\StepanCarService.Core\StepanCarService.Core.csproj" />
    <ProjectReference Include="..\StepanCarSevice.VisitService.Domain\StepanCarSevice.VisitService.Domain.csproj" />
  </ItemGroup>

</Project>
