<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7319755c-1f6f-47d7-9459-4d8a8bb4937a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.6" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\StepanCarService.Common.API\StepanCarService.Common.API.csproj" />
    <ProjectReference Include="..\StepanCarSevice.DetailService.Infrastructure\StepanCarSevice.DetailService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
