<Project Sdk="Microsoft.NET.Sdk">

  <!-- Тесты Auth. Пакеты тестов и TestKit подключает tests/Directory.Build.props -->

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Services\Auth\StepanCarSevice.AuthService.API\StepanCarSevice.AuthService.API.csproj" />
  </ItemGroup>

</Project>
