// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StepanCarSevice.VisitService.Infrastructure.DBContexts;

#nullable disable

namespace StepanCarSevice.VisitService.Infrastructure.Migrations
{
    [DbContext(typeof(VisitDBContext))]
    [Migration("20260228145701_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StepanCarSevice.VisitService.Domain.Entities.CarModelSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ManufactureId")
                        .HasColumnType("integer");

                    b.Property<int>("ManufactureSnapshotId")
                        .HasColumnType("integer");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameRU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearFrom")
                        .HasColumnType("integer");

                    b.Property<int>("YearTo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ManufactureSnapshotId");

                    b.ToTable("CarModelSnapshots");
                });

            modelBuilder.Entity("StepanCarSevice.VisitService.Domain.Entities.CarSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarModelId")
                        .HasColumnType("integer");

                    b.Property<int>("CarModelSnapshotId")
                        .HasColumnType("integer");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("OwnerSnapshotId")
                        .HasColumnType("integer");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarModelSnapshotId");

                    b.HasIndex("OwnerSnapshotId");

                    b.ToTable("CarSnapshots");
                });

            modelBuilder.Entity("StepanCarSevice.VisitService.Domain.Entities.DetailSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarModelId")
                        .HasColumnType("integer");

                    b.Property<int>("CarModelSnapshotId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CarModelSnapshotId");

                    b.ToTable("DetailSnapshots");
                });

            modelBuilder.Entity("StepanCarSevice.VisitService.Domain.Entities.ManufactureSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameRU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ManufactureSnapshots");
                });

            modelBuilder.Entity("StepanCarSevice.VisitService.Domain.Entities.OwnerSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OwnerSnapshots");
                });

            modelBuilder.Entity("StepanCarSevice.VisitService.Domain.Entities.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<int>("CarSnapshotId")
                        .HasColumnType("integer");

                    b.Property<string>("DateFrom")
                        .HasColumnType("text");

                    b.Property<string>("DateTo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("StepanCarSevice.VisitService.Domain.Entities.VisitDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DetailId")
                        .HasColumnType("integer");

                    b.Property<int>("DetailSnapshotId")
                        .HasColumnType("integer");

                    b.Property<int>("VisitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DetailSnapshotId");

                    b.HasIndex("VisitId");

                    b.ToTable("VisitDetails");
                });

            modelBuilder.Entity("StepanCarSevice.VisitService.Domain.Entities.Work", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("VisitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VisitId");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("StepanCarSevice.VisitService.Domain.Entities.CarModelSnapshot", b =>
                {
                    b.HasOne("StepanCarSevice.VisitService.Domain.Entities.ManufactureSnapshot", "ManufactureSnapshot")
                        .WithMany()
                        .HasForeignKey("ManufactureSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManufactureSnapshot");
                });

            modelBuilder.Entity("StepanCarSevice.VisitService.Domain.Entities.CarSnapshot", b =>
                {
                    b.HasOne("StepanCarSevice.VisitService.Domain.Entities.CarModelSnapshot", "CarModelSnapshot")
                        .WithMany()
                        .HasForeignKey("CarModelSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StepanCarSevice.VisitService.Domain.Entities.OwnerSnapshot", "OwnerSnapshot")
                        .WithMany()
                        .HasForeignKey("OwnerSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarModelSnapshot");

                    b.Navigation("OwnerSnapshot");
                });

            modelBuilder.Entity("StepanCarSevice.VisitService.Domain.Entities.DetailSnapshot", b =>
                {
                    b.HasOne("StepanCarSevice.VisitService.Domain.Entities.CarModelSnapshot", "CarModelSnapshot")
                        .WithMany()
                        .HasForeignKey("CarModelSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarModelSnapshot");
                });

            modelBuilder.Entity("StepanCarSevice.VisitService.Domain.Entities.Visit", b =>
                {
                    b.HasOne("StepanCarSevice.VisitService.Domain.Entities.CarSnapshot", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("StepanCarSevice.VisitService.Domain.Entities.VisitDetails", b =>
                {
                    b.HasOne("StepanCarSevice.VisitService.Domain.Entities.DetailSnapshot", "DetailSnapshot")
                        .WithMany()
                        .HasForeignKey("DetailSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StepanCarSevice.VisitService.Domain.Entities.Visit", "Visit")
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetailSnapshot");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("StepanCarSevice.VisitService.Domain.Entities.Work", b =>
                {
                    b.HasOne("StepanCarSevice.VisitService.Domain.Entities.Visit", "Visit")
                        .WithMany("Works")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("StepanCarSevice.VisitService.Domain.Entities.Visit", b =>
                {
                    b.Navigation("Works");
                });
#pragma warning restore 612, 618
        }
    }
}
