<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\StepanCarService.Common.Application\StepanCarService.Common.Application.csproj" />
    <ProjectReference Include="..\StepanCarSevice.DetailService.Domain\StepanCarSevice.DetailService.Domain.csproj" />
  </ItemGroup>

</Project>
