<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>44eb5a33-857e-46b0-b233-2a5856610f32</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.6" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\StepanCarService.Common.API\StepanCarService.Common.API.csproj" />
    <ProjectReference Include="..\..\..\Core\StepanCarService.Common.Core\StepanCarService.Common.Core.csproj" />
    <ProjectReference Include="..\StepanCarSevice.AuthService.Infrastructure\StepanCarSevice.AuthService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
