// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StepanCarSevice.DetailService.Infrastructure.DBContexts;

#nullable disable

namespace StepanCarSevice.DetailService.Infrastructure.Migrations
{
    [DbContext(typeof(DetailDbContext))]
    [Migration("20260915170028_AddedTenantOwner")]
    partial class AddedTenantOwner
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarModificationDetail", b =>
                {
                    b.Property<int>("CarModificationId")
                        .HasColumnType("integer");

                    b.Property<int>("DetailId")
                        .HasColumnType("integer");

                    b.HasKey("CarModificationId", "DetailId");

                    b.HasIndex("DetailId");

                    b.ToTable("CarModificationDetails", (string)null);
                });

            modelBuilder.Entity("CarModificationEngine", b =>
                {
                    b.Property<int>("CarModificationId")
                        .HasColumnType("integer");

                    b.Property<int>("EngineId")
                        .HasColumnType("integer");

                    b.HasKey("CarModificationId", "EngineId");

                    b.HasIndex("EngineId");

                    b.ToTable("CarModificationEngines", (string)null);
                });

            modelBuilder.Entity("DetailAlternativeLinks", b =>
                {
                    b.Property<int>("DetailId")
                        .HasColumnType("integer");

                    b.Property<int>("AlternativeDetailId")
                        .HasColumnType("integer");

                    b.HasKey("DetailId", "AlternativeDetailId");

                    b.HasIndex("AlternativeDetailId");

                    b.ToTable("DetailAlternativeRelations", (string)null);
                });

            modelBuilder.Entity("DetailOriginalLinks", b =>
                {
                    b.Property<int>("DetailId")
                        .HasColumnType("integer");

                    b.Property<int>("OriginalDetailId")
                        .HasColumnType("integer");

                    b.HasKey("DetailId", "OriginalDetailId");

                    b.HasIndex("OriginalDetailId");

                    b.ToTable("DetailOriginalRelations", (string)null);
                });

            modelBuilder.Entity("StepanCarService.Common.Core.Entities.TenantInfoEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("TenantInfoEntity");
                });

            modelBuilder.Entity("StepanCarSevice.DetailService.Domain.Entities.CarManufacture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("CarManufactures");
                });

            modelBuilder.Entity("StepanCarSevice.DetailService.Domain.Entities.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ManufactureId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<int>("YearFrom")
                        .HasColumnType("integer");

                    b.Property<int>("YearTo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ManufactureId");

                    b.HasIndex("TenantId");

                    b.ToTable("CarModels");
                });

            modelBuilder.Entity("StepanCarSevice.DetailService.Domain.Entities.CarModification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarModelId")
                        .HasColumnType("integer");

                    b.Property<string>("EnginePower")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<int>("TransmissionTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("WheelDriveTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarModelId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TransmissionTypeId");

                    b.HasIndex("WheelDriveTypeId");

                    b.ToTable("CarModifications");
                });

            modelBuilder.Entity("StepanCarSevice.DetailService.Domain.Entities.Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("DetailManufactureId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("DetailManufactureId");

                    b.HasIndex("TenantId");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("StepanCarSevice.DetailService.Domain.Entities.DetailManufacture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("DetailManufactures");
                });

            modelBuilder.Entity("StepanCarSevice.DetailService.Domain.Entities.Engine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarModelId")
                        .HasColumnType("integer");

                    b.Property<int>("EngineTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("EngineValue")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CarModelId");

                    b.HasIndex("EngineTypeId");

                    b.HasIndex("TenantId");

                    b.ToTable("Engines");
                });

            modelBuilder.Entity("StepanCarSevice.DetailService.Domain.Entities.EngineType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EngineTypes");
                });

            modelBuilder.Entity("StepanCarSevice.DetailService.Domain.Entities.TransmissionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TransmissionTypes");
                });

            modelBuilder.Entity("StepanCarSevice.DetailService.Domain.Entities.WheelDriveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WheelDriveTypes");
                });

            modelBuilder.Entity("CarModificationDetail", b =>
                {
                    b.HasOne("StepanCarSevice.DetailService.Domain.Entities.CarModification", null)
                        .WithMany()
                        .HasForeignKey("CarModificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StepanCarSevice.DetailService.Domain.Entities.Detail", null)
                        .WithMany()
                        .HasForeignKey("DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarModificationEngine", b =>
                {
                    b.HasOne("StepanCarSevice.DetailService.Domain.Entities.CarModification", null)
                        .WithMany()
                        .HasForeignKey("CarModificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StepanCarSevice.DetailService.Domain.Entities.Engine", null)
                        .WithMany()
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DetailAlternativeLinks", b =>
                {
                    b.HasOne("StepanCarSevice.DetailService.Domain.Entities.Detail", null)
                        .WithMany()
                        .HasForeignKey("AlternativeDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StepanCarSevice.DetailService.Domain.Entities.Detail", null)
                        .WithMany()
                        .HasForeignKey("DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DetailOriginalLinks", b =>
                {
                    b.HasOne("StepanCarSevice.DetailService.Domain.Entities.Detail", null)
                        .WithMany()
                        .HasForeignKey("DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StepanCarSevice.DetailService.Domain.Entities.Detail", null)
                        .WithMany()
                        .HasForeignKey("OriginalDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StepanCarSevice.DetailService.Domain.Entities.CarManufacture", b =>
                {
                    b.HasOne("StepanCarService.Common.Core.Entities.TenantInfoEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("StepanCarSevice.DetailService.Domain.Entities.CarModel", b =>
                {
                    b.HasOne("StepanCarSevice.DetailService.Domain.Entities.CarManufacture", "Manufacture")
                        .WithMany("CarModels")
                        .HasForeignKey("ManufactureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StepanCarService.Common.Core.Entities.TenantInfoEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacture");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("StepanCarSevice.DetailService.Domain.Entities.CarModification", b =>
                {
                    b.HasOne("StepanCarSevice.DetailService.Domain.Entities.CarModel", "CarModel")
                        .WithMany("CarModifications")
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StepanCarService.Common.Core.Entities.TenantInfoEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StepanCarSevice.DetailService.Domain.Entities.TransmissionType", "TransmissionType")
                        .WithMany()
                        .HasForeignKey("TransmissionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StepanCarSevice.DetailService.Domain.Entities.WheelDriveType", "WheelDriveType")
                        .WithMany()
                        .HasForeignKey("WheelDriveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarModel");

                    b.Navigation("Tenant");

                    b.Navigation("TransmissionType");

                    b.Navigation("WheelDriveType");
                });

            modelBuilder.Entity("StepanCarSevice.DetailService.Domain.Entities.Detail", b =>
                {
                    b.HasOne("StepanCarSevice.DetailService.Domain.Entities.DetailManufacture", "DetailManufacture")
                        .WithMany("Details")
                        .HasForeignKey("DetailManufactureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StepanCarService.Common.Core.Entities.TenantInfoEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DetailManufacture");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("StepanCarSevice.DetailService.Domain.Entities.DetailManufacture", b =>
                {
                    b.HasOne("StepanCarService.Common.Core.Entities.TenantInfoEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("StepanCarSevice.DetailService.Domain.Entities.Engine", b =>
                {
                    b.HasOne("StepanCarSevice.DetailService.Domain.Entities.CarModel", "CarModel")
                        .WithMany()
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StepanCarSevice.DetailService.Domain.Entities.EngineType", "EngineType")
                        .WithMany()
                        .HasForeignKey("EngineTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StepanCarService.Common.Core.Entities.TenantInfoEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarModel");

                    b.Navigation("EngineType");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("StepanCarSevice.DetailService.Domain.Entities.CarManufacture", b =>
                {
                    b.Navigation("CarModels");
                });

            modelBuilder.Entity("StepanCarSevice.DetailService.Domain.Entities.CarModel", b =>
                {
                    b.Navigation("CarModifications");
                });

            modelBuilder.Entity("StepanCarSevice.DetailService.Domain.Entities.DetailManufacture", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
